### ISSUE TITLE
Group attendance re-work

### ISSUE THREAD

**Issue by joelsteidl** [joelsteidl/PBC-CG-App#13]
Group attendance page has gone through an overhaul. Let me know when you've had a chance to check it out.

**Comment by grantpestka** [comment]
It looks a lot better!  Is there a way to click in to an attendees record of see their info, like neighborhood, race etc.  This would prob be most useful for Caleb / Juan.

**Comment by grantpestka** [comment]
I think I looked at the group page not the attendance page

**Comment by grantpestka** [comment]
now that im on the right page (https://cg.providencedenver.org/node/1824) I have a couple ideas.
