### ISSUE TITLE
Create specific permissions for attendance managers

### ISSUE THREAD

**Issue by joelsteidl** [joelsteidl/PBC-CG-App#16]
For group connection and group attendance record.

**Comment by joelsteidl** [comment]
This could probably use a little testing. Permissions for Attendance Managers are as follows:

1. Group - can view group(s) they are attendance managers for
2. Group Attendance Record - can view GAR for groups they are attendance managers for
3. Group Connection - can view and edit group connections that are part of a group they are attendance managers for

**Comment by grantpestka** [comment]
as far as I can tell i cant get to any thing but my stuff when logged in as attendance manager
