### ISSUE TITLE
Adding PCO link on Group pages (per person)

### ISSUE THREAD

**Issue by joelsteidl** [joelsteidl/PBC-CG-App#31]

**Comment by joelsteidl** [comment]
This should be showing up for the group admin role now. Just visit a group page.

**Comment by grantpestka** [comment]
yep!

**Comment by grantpestka** [comment]
the links to the group managers on the group list page [http://cg.providencedenver.org/user/5](url) is confusing to me though.  What is its purpose?

**Comment by joelsteidl** [comment]
I made it have the first and last name of the attendance manager instead of their Drupal username.
