### ISSUE TITLE
Cancel button on Add someone new

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#35]
[http://cg.providencedenver.org/find/individual/1/test1234/test1234/1?firstname=test1234&lastname=test1234](url)

**Comment by joelsteidl** [comment]
Any thoughts on where it should go on the page?

**Comment by joelsteidl** [comment]
I changed this page up a bit. Let me know what you think about the cancel link.

https://www.evernote.com/l/AMmv9BJVMWVLnK6sux-yRbkFNXhZ2rEbTP0

**Comment by grantpestka** [comment]
I think that is a good place for it.  The only thing I would change is making it a little bigger
