### ISSUE TITLE
"We did not meet" button on Group Attendance Record

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#37]
I think this will make the user experience easier.    A notes field to explain why would be nice too.  Also a distinction between canceled, not scheduled, Family Gathering etc might be helpful too.

**Comment by joelsteidl** [comment]
This has been added. It is currently a yes/no (my fault for not reading more). We could make the notes field say "notes/reason for not meeting" and leave it more open ended.

Its not the end of the world if you would like the additional options.

**Comment by grantpestka** [comment]
is there a way we could have a button similar to to update attendance button, but red, that says "We Did not Meet This Week"  and put the notes field under that?  I dont think we need to add any further detail unless they ask for it.  I am not sure what the options would be.

**Comment by joelsteidl** [comment]
Currently, all the form fields you see are part of the same form, so I'm not sure multiple "submit" buttons makes sense. I think even if you meet, the notes field could occasionally be useful. Is the multi-column form the confusing part? I could easily put all the fields in a the same column.

**Comment by grantpestka** [comment]
lets try single column.

**Comment by grantpestka** [comment]
I think having 2 buttons makes it feel more app like.  not essential, but I think it would make the User experience more strait forward

**Comment by joelsteidl** [comment]
After talking with Lauren, I made everything a single column. She felt like it was the least confusing.
