### ISSUE TITLE
Confirm Attendance Submission Button on confirmation page

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#38]
[https://cg.providencedenver.org/group/1/attendance/1857/finished](url)

It should redirect to a thank you page

without it I am not sure that I am done with out it

**Comment by joelsteidl** [comment]
It does this. Right? That is the thank you page. It shows you a review of attendance and has an option to edit.

**Comment by grantpestka** [comment]
Is there a way that we could add a button that says confirm that redirects them to a page where the only test is “ Thank you! you Community Group Attendance has been Recorded”?

Grant Pestka
Owner, Project Manager, Developer

grant@thetissilentdata.com
720-589-4073

**Comment by joelsteidl** [comment]
That was my intent with that page. Take a look again and let me know what you think.

I think the review screen accomplishes both and gives people a better sense of what they just filled out.

**Comment by joelsteidl** [comment]
For clarity, this is what that page looks like now.

https://www.evernote.com/l/AMlUqrQA4kJCno37GgbdQ2Pqcqr0FEbRkZw

**Comment by grantpestka** [comment]
Can we add “ If everything is correct close your browser window and you are done!”  or somethings like that?

Grant Pestka
Owner, Project Manager, Developer

grant@thetissilentdata.com
720-589-4073

**Comment by joelsteidl** [comment]
We can, but I feel like that is just how websites work. I'm not sure people have to be told what do after getting to that page.

Think about checking out in a shopping experience.

**Comment by grantpestka** [comment]
I guess its fine.

Grant Pestka
Owner, Project Manager, Developer

grant@thetissilentdata.com
720-589-4073
