### ISSUE TITLE
List of past Group Attendance Records on Group Page for admin user

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#43]
I was looking for a list of all the old attendance records for a group.  This functionality exists for the group admin on their dashboard, but having it on the group page, especially for admins, would make it possible to look into things with out having to use the content tab,  I think this would be particularly useful for Caleb.

I think a "block" with a header similar to "People in this Group"  called "Past Attendance Reports" is what we are looking for.  Im envisioning the content being like a content tab filtered to only show group attendance record

**Comment by joelsteidl** [comment]
Is this what you had in mind? http://cg.providencedenver.org/group/1

See the right column. It will show the latest 10 with pagination to all of the past ones.

**Comment by grantpestka** [comment]
That looks good
