### ISSUE TITLE
Create new value for "did you meet..."= Has not completed

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#45]
make it hidden 
make "did you meet..." required

**Comment by joelsteidl** [comment]
This is done. There is a new field on the backend that has...

1. Not Submitted
2. Yes
3. No

I copied the existing field values over. If it was marked as "yes" previously, I did a query to see if anyone was marked as "in attendance", if not, I marked things as "not submitted", which is more accurate.
