### ISSUE TITLE
dont sent email to inactive group admins

### ISSUE THREAD

**Issue by grantpestka** [joelsteidl/PBC-CG-App#46]

**Comment by joelsteidl** [comment]
This should be done now. I also stopped creating a group attendance record / individual attendance record if a group is inactive. The only issue I see is the need to be on top of switching status if they are on a temporary break.

**Comment by grantpestka** [comment]
ya,

we should recommend some policy around best practices for using the system

Grant Pestka
Owner | Project Manager | Developer
grant@thetissilentdata.com
